name: "Deploy"

env:
  ADDON_CONTAINER_NAME: addon-libp2p-ws-proxy
  CONTAINER_NAME: libp2p-ws-proxy
  BUILD_FROM_PROXY: node:20-alpine

on:
  push:
    branches:
      - dev

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Publish Addon Proxy
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target build \
            --docker-hub ghcr.io/pinoutltd \
            --image ${{ env.ADDON_CONTAINER_NAME }}-{arch} 
      - name: Build and Push Proxy Image 
        run: |
          docker build --build-arg BUILD_FROM=${{ env.BUILD_FROM_PROXY }} --tag ghcr.io/pinoutltd/${{ env.CONTAINER_NAME }}:latest -f build/Dockerfile .
          docker push ghcr.io/pinoutltd/${{ env.CONTAINER_NAME }}:latest




